# Deploy a NiFi cluster, a user secret and a ZooKeeper cluster and a respective
# ZNode `simple-nifi-znode` which will be referenced
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  image:
    productVersion: 3.8.0
  servers:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-nifi-znode
spec:
  clusterRef:
    name: simple-zk
---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: simple-nifi-admin-user
spec:
  provider:
    static:
      userCredentialsSecret:
        name: simple-nifi-admin-user-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-nifi-admin-user-secret
stringData:
  admin: supersecretpassword
---
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: simple-nifi
spec:
  image:
    productVersion: 1.21.0
  clusterConfig:
    authentication:
      - authenticationClass: simple-nifi-admin-user
    listenerClass: external-unstable
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
      autoGenerate: true
    zookeeperConfigMapName: simple-nifi-znode
  nodes:
    config:
    roleGroups:
      default:
        replicas: 2
